apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-volume
  labels:
    name: kube-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/log/kubelogs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-volume-claim
spec:
  storageClassName: manual
  selector:
    matchLabels:
      name: kube-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi